//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CncDataSave.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CncDataSave.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N60 X-20                                 ;Point 7
        ///N65 XN60 X-20                                 ;Point 7
        ///N65 X-10 Y-25                            ;Point 8
        ///N70 X-30 Y-15                            ;Point 9
        ///N80 X0 Y-40                              ;Point 10
        ///N85 G40 G90 X-20 Y-20                    ;Point 11
        ///N90 G00 Z50
        ///N95 Y100
        ///N100 M30
        ///N5 G00 G54 G64 G90 G17 X-20 Y-20 Z50     ;Point 1
        ///N10 S450 M03 F250 D01 (12.5 MM DIA)
        ///N15 C0
        ///N20 Z5
        ///N25 G01 Z0
        ///N30 Z-5
        ///N35 G42 G91 X20 Y20                       [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string BTCCalculation {
            get {
                return ResourceManager.GetString("BTCCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N5 G00 G54 G64 G90 G17 X-20 Y-20 Z50     ;Point 1
        ///
        ///
        ///N60 X-20                                 ;Point 7
        ///N65 X-10 Y-25                            ;Point 8
        ///NN60 X-20                                 ;Point 7
        ///N65 X-10 Y-25                            ;Point 8
        ///N70 X-30 Y-15                            ;Point 9
        ///N80 X0 Y-40                              ;Point 10
        ///N85 G40 G90 X-20 Y-20                    ;Point 11
        ///N90 G00 Z50N60 X-20                                 ;Point 7
        ///N65 X-10 Y-25                       [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string BTCDimension {
            get {
                return ResourceManager.GetString("BTCDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N60 X-20                                 ;Point 7
        ///N65 X-10 Y-25 N60 X-20                                 ;Point 7
        ///N65 X-10 Y-25                            ;Point 8
        ///N70 X-30 Y-15N60 X-20                                 ;Point 7
        ///N65 X-10 Y-25                            ;Point 8
        ///N70 X-30 Y-15                            ;Point 9
        ///N80 X0 Y-40                              ;Point 10
        ///N85 G40 G90 X-20 Y-20                    ;Point 11
        ///N90 G00 Z50
        ///N95 Y100
        ///N100 M30
        ///N5 G00 G54 G64 G90 G17 X-20 Y-20 Z50     ; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string BTCProcess {
            get {
                return ResourceManager.GetString("BTCProcess", resourceCulture);
            }
        }
    }
}
